# Theme configuration
name: 'example-modern'
display_name: 'Example Theme - Modern Warfare'
description: 'This serves to illustrate the basic contents of a theme package illustrating modern warfare. It is set in a generic middle eastern "war against terror" setting.'
data_files: [
  units: 'units.json',
  weapons: 'weapons.json',
  factions: 'factions.json',
  modifiers: 'mods.json',
  music: 'music.json',
  effects: 'effects.json'
]